### PR TITLE
chore: removed scheduled release

### PR DESCRIPTION
**Pull request by asaf92**
### Description

Removed the weekly release automation

### CODE REVIEW

**Comment by bastiandoetsch** [comment]
What's the reason?

**Review by bastiandoetsch — APPROVED** [review]
LGTM. Let's re-enable once we have more updates :)

**Review by michelkaporin — CHANGES_REQUESTED** [review]
Hey, what's the actual reason? You can disable the workflow temporarily when we're not releasing often.

**Comment by asaf92** [comment]
@michelkaporin 

What's easier?
1. Enable workflow -> Start workflow -> Wait 40 minutes -> Remember to disable workflow -> Done
2. Start workflow -> Done

**Comment by michelkaporin** [comment]
@asaf92 you don't need to do option 1 at all. The workflow is available via dispatch that allows you to run it manually already. When you disable it you just disable scheduled run, not the manual trigger.

Screenshot 2022-08-02 at 09 14 45

**Comment by asaf92** [comment]
@michelkaporin Thanks, I did not know that 👍

**Comment by michelkaporin** [comment]
Taking my words back, feel free to merge it in. Btw you don't need to wait 40 mins to disable workflow back.

**Review by michelkaporin — APPROVED** [review]

**Pull request merged**
